### ISSUE TITLE
Add gilles.renoux@orange.com  (GillesInnov35) to maintainers.md 

### ISSUE THREAD

**Issue by GillesInnov35** [camaraproject/KnowYourCustomer#1]
Hello,

could you add gilles.renoux@orange.com from Orange (GillesInnov35) to the maintainers list of KnowYourCustomer project.

Thanks

Gilles RENOUX

**Comment by hdamker** [comment]
Created #4, including also Efthymis Isaakidis from Deutsche Telekom.
