### ISSUE TITLE
[KYC Match] Will there be a minimum number of properties in the request body?

### ISSUE THREAD

**Issue by MsOlaAjibola** [camaraproject/KnowYourCustomer#101]
**Problem description**
Currently the schema for v0.1.1 mandates a request body but it does not mandate a minimum number of properties in the request body

**Possible evolution**
Define minimum number of properties in schema

**Alternative solution**
Clearly specify the expected response when request body is empty 

Ola (GSMA)

**Comment by ToshiWakayama-KDDI** [comment]
Hi @MsOlaAjibola ,

As discussed in the 25/June/2024 meeting, "at least one property must be included, in addition to phoneNumber".

@fernandopradocabrillo , @GillesInnov35 , please let me know if I am wrong, 

Best regards,
Toshi
KDDI

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , sorry for my late answer, my comments:
- Currently phoneNumber is not mandatory as it is provided in 3-Legged token, am I wrong ? 
- Yes, we could include a minProperties value as you propose.
