### ISSUE TITLE
KYC Match Readiness Checklist

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/KnowYourCustomer#107]
Include the checklist for meta-release Fall24, including documentation, ATPs and alignment with commonalities (0.4.0)

**Comment by jgarciahospital** [comment]
Code action points:

- (once #103 & #104 are merged)
- Include clarification of the scoring algorithm into API documentation: "Unless otherwise captured in the specification, score will use the Jaro-Winkler distance algorithm for all countries."
- Align with commonalities 0.4.0 (error handling mainly @rartych ?)

**Comment by jgarciahospital** [comment]
Documentation & versioning convention (Items 4-5) action points:

- N/A, ready

**Comment by jgarciahospital** [comment]
Basic API test cases & documentation  (item 7) action points:

- Pending to include 0.2.0 basic ATP proposal

**Comment by rartych** [comment]
>     * Align with commonalities 0.4.0 (error handling mainly @rartych ?)

I will check error responses.
I see that `info` and `servers` objects need to be aligned.

**Comment by jgarciahospital** [comment]
> Documentation & versioning convention (Items 4-5) action points:
> 
> * N/A, ready

Ready

**Comment by jgarciahospital** [comment]
> > Code (item 1-2-3) action points:
> > 
> > * (once [Align yaml with commonalities v0.3 #103](https://github.com/camaraproject/KnowYourCustomer/pull/103) & [Include score functionality proposal #104](https://github.com/camaraproject/KnowYourCustomer/pull/104) are merged)
> > * Include clarification of the scoring algorithm into API documentation: "Unless otherwise captured in the specification, score will use the Jaro-Winkler distance algorithm for all countries."
> > * Align with commonalities 0.4.0 (error handling mainly @rartych ?)
> 
> Points fixed in [d014a3c](https://github.com/camaraproject/KnowYourCustomer/commit/d014a3cf1677984c5578b4e1d794e317a7346ca2) and [1a9c4c9](https://github.com/camaraproject/KnowYourCustomer/commit/1a9c4c931ac09e810a9de0038ea0670c08f63785)

To be included by meta-release version, after 0.2 publication

**Comment by rartych** [comment]
Fixes for info and servers objects and security scope names proposed in https://github.com/camaraproject/KnowYourCustomer/pull/114
