### ISSUE TITLE
Do Tenure API, NumberRecycling API and Shutdown Service Status API fit in KYC Family /KYC SP meeting?

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#109]
**Problem description**
In KYC SP meeting on 9th July 2024, it was shared that API Backlog WG is discussing if **NumberRecycling API** and **Shutdown Service Status API** fit in KYC Family /KYC SP meetings, in addition to **Tenure API**, because thse three APIs have similar aspects that relate to KYC information.

From KDDI side (KYC SP facilitator, NumberRecycling API lead), **they will fit in KYC Family/ KYC SP meeting, and KYC SP can accept them**.  (Note: Tenure has been accepted already.)

**Expected action**
**If anyone have different views, please comment**, if possible, by the next API Backlog meeting to be held on **11th July Thursday, from 10:00 CEST**.

**Additional context**
About three APIs:
**-Tenure API (Vodafone lead, OGW Drop#4)**: API Backlog Issue #2 (https://github.com/camaraproject/APIBacklog/issues/2)
**-NumberRecycling API (KDDI lead, OGW Drop#4)**: API Backlog Issue #54 (https://github.com/camaraproject/APIBacklog/issues/54)
**-ShuatdownServiceStatus API (China Unicom lead, OGW Drop#4)**: API Backlog Issue #34 (https://github.com/camaraproject/APIBacklog/issues/34)

-and my colleague Tet Chiba has created **a document comparing three APIs**:
https://github.com/camaraproject/APIBacklog/issues/54#issuecomment-2194277111

Many thanks,
Toshi
KDDI

**Comment by eric-murray** [comment]
I discussed this within Vodafone, and we see synergies between all three of these APIs. Given that Tenure is already part of the KYC sub-project, it therefore makes sense that both Number Recycling and Shutdown Service Status also be part of this sub-project. Shutdown Service Status is not yet approved, of course.

Should the inclusion of these APIs overload the KYC meetings, I see two options:
- A separate "sub-meeting" series for Tenure / Number Recycling / Shutdown Service Status, which then presents a summary of these meetings to the main meeting for any further discussion there
- Or the three APIs could be spun out into their own separate sub-project

However, we should start with them being on the agenda for the main meetings and, if time proves to be an issue, then the above options can be discussed further.

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @eric-murray , for your comments.

I would agree: 

> we should start with them being on the agenda for the main meetings and, if time proves to be an issue, then the above options can be discussed further.

Thanks,
Toshi

**Comment by jgarciahospital** [comment]
As agreed in the group discussion (please correct if mistaking):

- Tenure repo is created. Issues and PRs to be maintained directly in the proper subproject: https://github.com/camaraproject/Tenure
- NumberRecycling repo is created. Issues and PRs to be maintained directly in the proper subproject: https://github.com/camaraproject/NumberRecycling
- Shutdown Service pending to create repo. Backlog admins will get in touch with API supporters to find CodeOwner/Maintainers, and will follow similar strategy as previous APIs. Name change to be confirmed (Subscription Status).

As agreed in the conversation, KYC family meetings can be used as follow-up tracker for the hole set of APIs (KYC-Match, KYC-Fill-In, Age Verification, Tenure, Number Recycling, Shutdown Service, final decision on meetings will take place after some running time. 

@camaraproject/api-backlog_maintainers

**Comment by ToshiWakayama-KDDI** [comment]
Closing this issue, as discussed on 2024-09-17.  We will revisit this topic after some running time to see how it will be going. 

Thanks.
