### ISSUE TITLE
[KYC Match / KYC Fill-in] givenName appears as giventName in specification examples 

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/KnowYourCustomer#117]
**Problem description**

* KYC Match - [givenName](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-match.yaml#L219) is a request attribute in the schema. However in the request example it is known as [giventName](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-match.yaml#L103). 
* KYC Fill-In - [givenName](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-fill-in.yaml#L181) is a request attribute in the schema. However in the request example it is known as [giventName](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-fill-in.yaml#L110). 

**Expected behavior**

Example in specification to be corrected

**Comment by ToshiWakayama-KDDI** [comment]
Hi @trehman-gsma ,

Thank you for pointing them out.

Hi @jgarciahospital , @fernandopradocabrillo ,

In addition, I saw that KYC_Match 200 response Example has float numbers for Scoring, so, we need to correct them (to integer numbers).

Can these corrections be covered by the RC PR I suppose you are preparing?  If not, I will create a separate PR for them.

Many thanks,
Toshi

**Comment by fernandopradocabrillo** [comment]
Hi @trehman-gsma, I've fixed the typo in #119 thanks for pointing it out

@ToshiWakayama-KDDI examples are also fixed in the same PR, thanks!

**Comment by ToshiWakayama-KDDI** [comment]
Closed as this issue has been fixed by PR #119.
