### ISSUE TITLE
KYC Match : CountryMatchScore makes no sense

### ISSUE THREAD

**Issue by HuubAppelboom** [camaraproject/KnowYourCustomer#134]
In the current list of attributes for which a MatchScore can be supplied in case the Match is false, also Country is included.

Country is however now become formatted as ISO 3166-1 alpha-2, so I don't think it makes much sense here to supply a MatchScore anymore

**Comment by GillesInnov35** [comment]
@HuubAppelboom, I wonder if we should not apply the same rules for streetNumber and remove streetNameMatchScore as it will be done for countryCode and postalCode. 
BR 
Gilles

**Comment by HuubAppelboom** [comment]
@GillesInnov35 Do you mean streetNameMatchScore or streetNumberMatchScore ?  

For streetNameMatchScore we definitely see a need to provide it, since streetName may contain spelling mistakes.

For streetNumberMatchScore we had some doubts, but since it is now defined as a  string people may enter here what we consider the houseNumberExtension.  

We think that maybe it is better to see how people will use it, and we can always remove it in future when it is not being used. 

In retrospect it may have been better to define streetNumber as an integer as wel...

Best regards
Huub

**Comment by GillesInnov35** [comment]
thanks Huub, yes it concerns streetNumberMatchScore (sorry for the mistake).
As you say, if streetNumber moves to an a **_integer_** type, streetNumberMatchScore should not be useful. TMF geographicAddress's design proposes a streetNrSuffix, currently there's no streetNumberSuffix in kyc-match design. It means that streetNumber should remain a **_string_** type (perhaps). We can see how streetNumber will be managed as you propose.
BR
Gilles

**Comment by HuubAppelboom** [comment]
Yes, and we also have still houseNumberExtension that parties can use
