### ISSUE TITLE
Start using LF Confluence for agenda and minutes

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/KnowYourCustomer#136]
**Problem description**

At some point we should swift the minutes to the Confluence page. We've done this for the rest of the WGs. It would be easier to maintains as well since @ToshiWakayama-KDDI won't have to create PRs to upload documents, wait for us to approve, etc. And the agenda and minutes would be in the same place. For example: https://wiki.camaraproject.org/pages/viewpage.action?pageId=34734375

**Expected action**

Start using the CAMARA confluence page

**Additional context**

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @fernandopradocabrillo .  You are completely right.  Moving agenda and minutes to LF Confluence has been considered since some months ago.  I will do this once Fall24 Meta rush ends.

Best regards,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Closed, as agreed at the SP meeting on 2024-10-01.
