### ISSUE TITLE
Bad URL for User stories and Basic API test cases link in kyc-match-API-Readiness-Checklist.md  and in kyc-fill-in-API-Readiness-Checklist.md

### ISSUE THREAD

**Issue by GillesInnov35** [camaraproject/KnowYourCustomer#159]
**Problem description**
Bad URL for User stories and Basic API test cases link in **kyc-match-API-Readiness-Checklist.md**  and in **kyc-fill-in-API-Readiness-Checklist.md**

https://github.com/camaraproject/KnowYourCustomer/blob/r1.3/documentation/API_documentation/documentation/API_documentation/KnowYourCustomer_User_Story.md
https://github.com/camaraproject/KnowYourCustomer/blob/r1.3/documentation/API_documentation/code/Test_definitions/kyc-match.feature

**Expected behavior**
remove _**documentation/API_documentation/**_ from the URL because twice

**Comment by fernandopradocabrillo** [comment]
If we do a small release r1.4 fixing the test plan for v0.2.1 we can include this issue there and solve it. wdyt?
