### ISSUE TITLE
KYC Match - KYC Match Request / Response attribute suffix

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#22]
We also need to agree with KYC Match Request / Response attribute suffix for KYC Match API attributes which are being discussed in Issue #18.

According to our past discussions on Issue #18, we have the following proposals:

**Match Request Body**

| **MNO** | **Match Request** | **Match Response** | **Remarks** |
| ------- | ----------------- | ------------------ | ----------- |
|**KDDI** | xxxxxMatch | xxxxxMatch | for Fill-in, xxxxx (no suffix) is proposed |
|**Orange**| xxxxx (no suffix) | xxxxxScore (*) | Match score is for future enhancement |
|**Telefoncia**| xxxxx (no suffix) | xxxxxResponse | |

<br>
<br>

KDDI would like to keep proposing Request:xxxxxMatch and Response:xxxxxMatch, because in the future versions, we may have new features like Match scoring and Hashing and we can differentiate them by adding certain suffixes in the same way, e.g. xxxxxScore or xxxxxHash.

Also, if we would expand the KYC Match API including different features in the same request body, e.g. phoneNumberMatch:aaaaaaa, addressScore:bbbbbbbb, nameHash:cccccc, it would be better to have suffixes not only for Response attributes but also Request attributes.

So, KDDI's proposal is Request:xxxxxMatch and Response:xxxxxMatch.

Any other viewes are welcome, to agree by our next meeting on 12nd December.

Many thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,

Thanks very much for your comment.  But I am confused.  Your comment above (https://github.com/camaraproject/KnowYourCustomer/issues/22#issuecomment-1843098001) and your comment for PR #25 (https://github.com/camaraproject/KnowYourCustomer/pull/25#pullrequestreview-1769505814, "match both in request and response") are opposite, by my understanding.

Could you clarify this, please?

Thanks,
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , I was meaning that I've given my opinion in a previous comment, sorry it was not clear.
I think that the name of the attributes should not be the same when definitions are different.
Thanks a lot 
BR

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,

I am very sorry, but still unclear to me.  So, you prefer (A) below, right?  Not (B).

(A)
| **attribute** | **Match Request** | **Match Response** |
| ------- | ----------------- | ------------------ |
|**given name** | givenName | givenNameMatch |

(B)
| **attribute** | **Match Request** | **Match Response** |
| ------- | ----------------- | ------------------ |
|**given name** | givenNameMatch | givenNameMatch |

Thanks.
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , yes that's it. Thanks a lot
To all, What do you think about that ?

**Comment by ToshiWakayama-KDDI** [comment]
Hi all,
As it seems there is no other comment, I think we can conclude this point as below:

| **attribute** | **Match Request** | **Match Response** |
| ------- | ----------------- | ------------------ |
|**attribute** | attribute | attributeMatch |
|**e.g. given name** | givenName | givenNameMatch |

Please let us know if my understanding is wrong.

Many thanks,
Toshi

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , OK for me, Thanks a lot

**Comment by fernandopradocabrillo** [comment]
hi @ToshiWakayama-KDDI, as stated in the meeting we believe that the suffix in the response properties doesn't add value in terms of API design but it won't be a blocker from our side.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo ,
Thank you for your understanding.  I understand your view.  As we discussed yesterday, some members think the suffix adds value, and whether the suffix adds value or not is a subjective matter.  
(But I thought 'the responses would be xxxx_response for each of them' in https://github.com/camaraproject/KnowYourCustomer/issues/18#issuecomment-1817003858 is Telefonica's view.)


@All,
As we agreed at the meeting yesterday, we will adopt the follwoing suffix for our KYC Match API initial version:
| **attribute** | **Match Request** | **Match Response** |
| ------- | ----------------- | ------------------ |
|**attribute** | attribute | attributeMatch |
|**e.g. given name** | givenName | givenNameMatch |

Thank you for your cooperation.

**Comment by StefanoFalsetto-CKHIOD** [comment]
I am very sorry to revamp a thread already discussed but I have a question: don't you find misleading the fact that the attribute name of the match request is the same as in the fill-in version? Same attribute request, different responses depending on the service version.

**Comment by GillesInnov35** [comment]
hi @StefanoFalsetto-CKHIOD, to your point
>don't you find misleading the fact that the attribute name of the match request is the same as in the fill-in version?

Could you clarify What you mean by:
>Same attribute request, different responses depending on the service version.

Naming of attribute has been normalized and we should use same attribute's name for the same concept.
A givenName provided in Match request has the same definition/description in the Fill-In reponse according to the MNO data model. Did I understand the question correctly?
Thanks
Gilles

**Comment by StefanoFalsetto-CKHIOD** [comment]
Hi @GillesInnov35 I'm sorry for the late response, but I didn't received any notification for your comment.

Maybe an example could help:
- In KYC fill-in you ask "please give me a name" and MNO gives you a "name". So you ask for a "name" and you obtain a "name".
- In KYC match you ask "does this string (or hash) matches with the one the MNO is storing in their backends?". Even if the request is quite different, you ask for a "name" and you obtain a "true/false". 

In my point of view a match request is different from a fill-in, hence in case of a match I would prefer to have a format like <attribute_name>_match to make clear that the response you can obtain is not a string representing an attribute but a match result.

**Comment by GillesInnov35** [comment]
hi @StefanoFalsetto-CKHIOD, thanks a lot for your comment.

> In KYC match you ask "does this string (or hash) matches with the one the MNO is storing in their backends?". Even if the request is quite different, you ask for a "name" and you obtain a "true/false".

To my point of view, KYC Match doesn't  ask for a "**_name_**" but provide a name for comparison with **_name_** held by the MNO. So concept is the same as Fill-In. I beleive we must normalize naming convention as much as possible.
To all, your point of view ?
BR
Gilles

**Comment by StefanoFalsetto-CKHIOD** [comment]
Hi @GillesInnov35. In KYC Match you don't expect a "name" from the MNO to be compared with your values. You expect just an answer: match/no match. More precisely: the comparison is not performed by the Provider but it is done by the MNO (or anyone on its behalf). The concept is not the same as fill-in. In fill-in request you don't send any value and you expect a set of attributes, on the other side in KYC match you send a attributes to match and expect a match result.

**Comment by ToshiWakayama-KDDI** [comment]
Hi all,

May I understand there is no outstanding topics in this issue and this issue can be closed?

BR
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI, for my understanding yes we can close this issue but I let @StefanoFalsetto-CKHIOD answer too.
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Closed as we discussed.
