### ISSUE TITLE
KYC Fill-in Specifications

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#23]
**Problem description**

There is only one proposal from KDDI for KYC Fill-in, so the initial version of KYC Fill-in will be KDDI's YAML base.  However, some alignment to KYC Match API is needed, which can be discussed in this issue.

First of all, parameters/attributes for KYC Fill-in API should be agreed.  It is believed that the general rule would be that **parameters/attributes for KYC Fill-in API should be aligned with those of KYC Match API where applicable**.

If you think this general rule is not appropriate, please give your view and alternative ideas.

Many thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,

Thank you for your commment.  Could you explain a bit more about 'except what the phone number'?  Do you use a different attribute name?

Thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi all,

I would like to propose Fill-in API flows for our first version API documentation, as attached.  It is very straightforward, highlevel and generic flow, which could apply to any use cases for Fill-in.

Any comments are welcome.

Note: It was created by PowerPoint and captured as a picture, because I am not familiar with tools for drawing flows.  Please let us know if you are familiar with tools.

<img width="854" alt="KYC_Fill-in_flow" src="https://github.com/camaraproject/KnowYourCustomer/assets/53090722/230177ae-2fb8-4833-9beb-c82d3930bc1d">

Many thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi all,
Regarding the parameters/attributes for KYC Fill-in API, as we are finalising those for KYC Match API, we can adopt the same ones for KYC Fill-in API as below:

- **phoneNumber**
- **mainPhoneNumber**
- **idDocument**
- **name**
- **nameKanaHankaku**
- **nameKanaZenkaku**
- **givenName**
- **middleNames**
- **familyName**
- **postalCode**
- **address**
- **streetName**
- **streetNumber**
- **region**
- **locality**
- **country**
- **birthdate**
- **email**
- **givenNameInitial**
- **middleNamesInitials**
- **familyNameAtBirth**
- **houseNumberExtension**
- **gender**
- **cp_id**

Please let us know if you have any other ideas.

Many thanks,
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , as the API return the same type of value as the Match request, why shoudn't we return the same attribute ?


| **attribute** | **Fill-in Response** |
| ------- | ----------------- |
|**attribute** | attribute in response |
|**e.g. given name** | givenName |

**Comment by ToshiWakayama-KDDI** [comment]
Closed as agreed.
