### ISSUE TITLE
KYC Match - Response Codes

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#24]
**Problem description**

Hi all,

We have to agree with Response Codes for KYC Match API as soon as possible.  To start discussion, I have created a table for comparing Telefonica proposal (derieved from Telefonica YAML) and KDDI proposal (derived from KDDI YAML) and a consolidated proposal. 

Any comments are welcome.

| **HTTP Result** | Telefonica Proposal (from YAML) | KDDI Proposal (from YAML) | **KYC Match Consolidated Proposal** |
| ------- | ----------------- | ------------------ | ----------- |
|**400** | Problem with the client request | Problem with the client request | **400** |
|    | Code: INVALID_ARGUMENT <br> Message: Client specified an invalid argument, request body or query param  | Code: INVALID_CHARACTERS/INVALID_PARAMS <br> Message: invalid_characters/invalid_params  | **Code: INVALID_ARGUMENT <br> Message: Client specified an invalid argument, request body or query param**  |
|    | Code: KNOW_YOUR_CUSTOMER.INVALID_PARAM_COMBINATION <br> Message: Indicated parameter combination is invalid   |     | **Code: KNOW_YOUR_CUSTOMER.INVALID_PARAM_COMBINATION <br> Message: Indicated parameter combination is invalid**   |
|    |    |     | **Code: INVALID_CHARACTERS/INVALID_PARAMS <br> Message: invalid_characters/invalid_params**    |
|**401** | Authentication problem with the client request  | Unauthorized error.  Access Token related errors.    | **401** |
|    | Code: UNAUTHENTICATED <br> Message: Request not authenticated due to missing, invalid, or expired credentials   | Code: INVALID_TOKEN <br> Message: invalid_token    |**Code: UNAUTHENTICATED <br> Message: Request not authenticated due to missing, invalid, or expired credentials**     |
|    |    | Code: EXPIRED_TOKEN <br> Message: expired_token    |**Code: INVALID_TOKEN <br> Message: invalid_token**     |
|    |    |     |**Code: EXPIRED_TOKEN <br> Message: expired_token**     |
|**403**  |Client does not have sufficient permission    |     |**403**     |
|    |Code: PERMISSION_DENIED <br> Message: Client does not have sufficient permissions to perform this action    |     |**Code: PERMISSION_DENIED <br> Message: Client does not have sufficient permissions to perform this action**     |
|    |Code: KNOW_YOUR_CUSTOMER.INVALID_TOKEN_CONTEXT <br> Message: Phone number mismatch with access token context    |     |**Code: KNOW_YOUR_CUSTOMER.INVALID_TOKEN_CONTEXT <br> Message: Phone number mismatch with access token context**     |
|    |Code: NOW_YOUR_CUSTOMER.ID_DOCUMENT_REQUIRED <br> Message: The idDocument is required to perform the properties validation    |     |**Code: NOW_YOUR_CUSTOMER.ID_DOCUMENT_REQUIRED <br> Message: The idDocument is required to perform the properties validation**     |
|    |Code: KNOW_YOUR_CUSTOMER.ID_DOCUMENT_MISMATCH <br> Message: The idDocument needs to match the one associated with the provided phoneNumber    |     |**Code: KNOW_YOUR_CUSTOMER.ID_DOCUMENT_MISMATCH <br> Message: The idDocument needs to match the one associated with the provided phoneNumber**     |
|**404**    |    | Not Found error.  Error if URL is wrong / user is not found.    |**404**     |
|    |    | Code: NOT_FOUND <br> Message: not_found_contractor/not_found    |**Code: NOT_FOUND <br> Message: not_found_contractor/not_found**     |
|**500**    |Server error    |Internal server error.  Problem with MNO's server side.  Some processing error within MNO's servers.     |**500**     |
|    |Code: INTERNAL <br> Message: Server error    | Code: MAINTENANCE <br> Message: System maintenance    |**Code: INTERNAL <br> Message: Server error**     |
|    |    |Code: MAINTENANCE <br> Message: Service maintenance     |**Code: MAINTENANCE <br> Message: System maintenance**     |
|    |    |     |**Code: MAINTENANCE <br> Message: Service maintenance**     |
|**503**    |Service unavailable.  Typically the server is down.    |Service Unavailable.  Problem with MNO's server side.  Any unexpected error within MNO's servers.     |**503**     |
|    |Code: UNAVAILABLE <br> Message: Service unavailable    |Code: UNAVAILABLE <br> Message: sorry_error     |**Code: UNAVAILABLE <br> Message: Service unavailable**     |
|    |    |     |**Code: UNAVAILABLE <br> Message: sorry_error**     |
|**504**    |Request time exceeded.  If it happens repeatedly, consider reducing the request complexity    |     |**504**     |
|    |Code: TIMEOUT <br> Message: Request timeout exceeded.  Try later.    |     |**Code: TIMEOUT <br> Message: Request timeout exceeded.  Try later.**     |

Many thanks,
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , I see that most of the code/message errors follow CAMARA commonalities guidelines, that's good.
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#6-error-responses

 ****But some of them are specific, for example:**** 
Code: NOW_YOUR_CUSTOMER.ID_DOCUMENT_REQUIRED
Message: The idDocument is required to perform the properties validation

I'm not sure we should complete the CAMARA list, but perhaps I'm wrong. 
Thanks for your implication.
BR

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,
I am not completely sure, but I do not think we should complete the CAMARA list.  If we should, we can revise API difinition in a update version.

Hi all,
As it seems there is no other comment, I think we can use the above Response Codes for our initial version.

Please let us know if my understanding is wrong.

Many thanks,
Toshi

**Comment by fernandopradocabrillo** [comment]
Hi @ToshiWakayama-KDDI ,
Here I leave my comments on each error

**400**:
Code: INVALID_ARGUMENT
Message: Client specified an invalid argument, request body or query param

Code: KNOW_YOUR_CUSTOMER.INVALID_PARAM_COMBINATION
Message: Indicated parameter combination is invalid

In camara this one is included in INVALID_ARGUMENT
~~Code: INVALID_CHARACTERS/INVALID_PARAMS~~
~~Message: invalid_characters/invalid_params~~

**401**:
Code: UNAUTHENTICATED
Message: Request not authenticated due to missing, invalid, or expired credentials

In camara these are included in UNAUTHENTICATED:
~~Code: INVALID_TOKEN~~
~~Message: invalid_token~~

~~Code: EXPIRED_TOKEN~~
~~Message: expired_token~~

**403**:
Agree with the proposed list

**404**:
Agree with the proposed list

**500**:
I can see that in other camara APIs only this one is being used at the moment:
Code: INTERNAL
Message: Server error

**503**:
Agree with this one. The property "message" is free text so it can cover multiple cases:
Code: UNAVAILABLE
Message: Service unavailable

**504**:
Agree with the proposed list

Thanks!

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo ,

Thank you for your comments.  I understand you referred to the CAMARA API Design guidelines and your comments make sense.  I agree to your comments and I will modify the consolidated YAML soon.

Best regards,
Toshi

**Comment by GillesInnov35** [comment]
hi all, I agree also with the proposal, thanks
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Closed as agreed.
