### ISSUE TITLE
KYC Match - API Flow

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#26]
**Problem description**
We need agreed KPI Match Flows for our first version API documentation. 

I woud like to propose it as attached.   It is very straightforward, highlevel and generic flow, which could apply to any use cases for KYC Match.

Any comments are welcome.

Note: It was created by PowerPoint and captured as a picture, because I am not familiar with tools for drawing flows.  Please let us know if you are familiar with tools.

<img width="848" alt="KYC_Match_flow" src="https://github.com/camaraproject/KnowYourCustomer/assets/53090722/9850eaaf-a8d4-4f8e-9017-c6855f75b94d">

Many thanks,
Toshi

**Comment by GillesInnov35** [comment]
Thanks @ToshiWakayama-KDDI for your work. I usually use DrawIO for UML flows.

**Comment by GillesInnov35** [comment]
I've tried to put your proposition in a drawio schema. **_To be reviewed_**

**KYC Fill-in flows**
![KYC Fill-In flows](https://github.com/camaraproject/KnowYourCustomer/assets/144710412/e62f6a77-2a12-449f-9c96-8bf3957f48e2)

**KYC Match flows**
![KYC Match flows](https://github.com/camaraproject/KnowYourCustomer/assets/144710412/8f920252-346e-490a-9cd3-b3cac87ab238)

**Comment by tcchiba** [comment]
Hi @GillesInnov35, Thank you for your drawing.

The application provisioning sequence and the 3 legged authentication sequence are common to other APIs. Therefore, for the purpose of simplicity, why not omit these and draw only the KYC Fill-in and the KYC Match sequences themselves?

BR
Tet, KDDI

**Comment by GillesInnov35** [comment]
hi @tcchiba , thanks for your comment. Yes you're right. As Toshi mentionned the authentication flows in the previous schema he has proposed I thought also it was useful to show which credentials were used (client id/client secret) and the user consent.
I'll remove the authentication and authorization sequence if decision is that it is not useful.
BR
Gilles

**Comment by GillesInnov35** [comment]
@tcchiba, in fact the proposition made by @ToshiWakayama-KDDI was good and simple. We might keep this schema.
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Closed as agreed.
