### ISSUE TITLE
Organise meeting please

### ISSUE THREAD

**Issue by MarkCornall** [camaraproject/KnowYourCustomer#5]
Hi All, 
please can you start the regular meetings on this API with priority.
Thank you
Mark

**Comment by ToshiWakayama-KDDI** [comment]
Hi @MarkCornall, 
I will organise the regular meetings quickly.
Thank you.

Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Close this issue as the regular meetings started on 31st October 2023.
