### ISSUE TITLE
Remove phoneNumberMAtch field from response schema

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/KnowYourCustomer#59]
**Problem description**
The proposal is to remove the property `phoneNumberMatch` from the response schema since we believe it is not necessary. What is it going to match against? if the phoneNumber provided doesn't match the one in the token the API will return a 403. And the client should not be able to send a phone number different from the one that the user is authenticated with, it will always return 403.

So `phoneNumberMatch` will always return true since the phone number will always have to match otherwise there won't be a 200.

**Comment by GillesInnov35** [comment]
hi @fernandopradocabrillo, I agree with you that the question must be asked, to have a design as simple as possible.
At Orange the API Match ID doesn't return any phoneNumberMatch score. But in France we see that some operators which proposed a KYC Match API have made the choice to return a phoneNumberMatch score valued to 100.
I think also that phoneNumberMatch should not be returned. 
Thanks 
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo , Hi @GillesInnov35 ,
 
We have reviewed this internally, and we agree with this proposal.  There may be no harm if it exists (always True response), but it is fine with us to remove it (phoneNumberMatch attribute).

I do not think there will be other comments especially opposing ones, so, will you create a PR for this?  (Or, shall I?)

Best regards,
Toshi
KDDI

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , thanks a lot.
