### ISSUE TITLE
Age Verification API

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/KnowYourCustomer#7]
**Problem description**
No problem but instead sync within the team.
As it was validated by GSMA Product stream, a new API for Age Verification was proposed in the API backlog (here: https://github.com/camaraproject/WorkingGroups/pull/323).

In this API we proposed to add this one in this KYW work group.

**Possible evolution**
As of now, nothing to do except agreement to manage also this API here if validated. As this API proposal has not been yet discussed and validated by TSC there is not real work to begin for this topic.

**Alternative solution**

**Additional context**
Looking for supporter for this API.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @bigludo7,

Thanks for the information.

I unerstand that the New API onboarding process is: 
https://github.com/camaraproject/Governance/blob/main/documentation/API-onboarding.md  .

Is the next TSC on 16th Nov going to decide which subproject Age Verification will go to?

Slight concern with having it here is that we have two ongoing APIs (KYC Match, Fill-in) and we don't have much time til December deadline.

**Comment by bigludo7** [comment]
Hello @ToshiWakayama-KDDI 
Thanks for your answer.

Yes the proposal will be discussed in next TSC.
From my perspective we should avoid to create too many sub-project and as Age Verification is linked to customer data it makes sense for me to add this API in our sub-project.
But I'm full sharing your concern about the deadlines for the 2 first API. Could we agreed on the following proposal that we can propose to the TSC:

- OK to add the Age verification API in KYC subproject
- **but** work here will only begin when a stable yaml are available for the first 2 APIs that are priority 1 for this sub-project,
- As such, age Verification work could not start probably before second end of December or early January

WDYT?
Thanks

cc: @GillesInnov35

**Comment by ToshiWakayama-KDDI** [comment]
Hi @bigludo7 , cc @GillesInnov35 
Thanks.  The proposal to the TSC would be fine with me.

Thanks.

**Comment by ToshiWakayama-KDDI** [comment]
As shared at 2023-11-28 meeting, TSC 2023-11-16 decided that KYC Age Verification API would belong to KnowYourCustomer Subproject, under the condition that Age Verification work will not start before stable YAMLs for currently ongoing KYC Match and KYC Fill-in become available.

Note from TSC 2023-11-16 minutes:
- New proposal "KYC Age Verification", see message https://lists.camaraproject.org/g/tsc/message/71
- Discussions: (Ludovic) Work on this API will not begin before end of this year/early next year. Toshi welcome this addition for the subproject. Current API Match & Fill-in are currently prioritized.
- DECISION: Approved

->Close this issue.
