### ISSUE TITLE
Cyclic reference in location-verification

### ISSUE THREAD

**Issue by RobertoSngular** [camaraproject/KnowYourCustomer#70]
The schema Area refence Circle and Circle reference Area properties

Circle probably doenst need Area properties

I fixed it like this:

    Area:
      type: object
      properties:
        areaType:
          $ref: "#/components/schemas/AreaType"
      required:
        - areaType
      discriminator:
        propertyName: areaType
        mapping:
          CIRCLE: "#/components/schemas/Circle"

    AreaType:
      type: string
      description: Type of this area. CIRCLE - The area is defined as a circle.
      enum:
        - CIRCLE

    Circle:
      description: Circular area
      type: object
      properties:
        center:
          $ref: "#/components/schemas/Point"
        radius:
          type: integer
          description: Expected accuracy for the verification in meters, from location (radius)
          minimum: 2000
          maximum: 200000
      required:
        - center
        - radius

**Comment by fernandopradocabrillo** [comment]
Hi @RobertoSngular, 
I think this is in the wrong WG. It seems that this belongs to [Device Location](https://github.com/camaraproject/DeviceLocation/tree/main)

**Comment by RobertoSngular** [comment]
You are absolutly rigth. i am sorry!
