### ISSUE TITLE
Select API for CAMARA Meta-Release September

### ISSUE THREAD

**Issue by GillesInnov35** [camaraproject/KnowYourCustomer#75]
**Problem description**

I wonder about the list of KYC API which should be elected for Meta Release of September.
From what I understand in our discussions, few contributors/MNOs won't implement KYC Fill-In API according to local privacy policy.

Do you think this API should be elected to the September Meta Release ?
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,  all, 

Thanks very much, Gills, for raising this issue.  

We hope KYC Fill-in API will be included in the September Meta Release.  Are there any contributors/MNOs thinking of implementing KYC Fill-in API?

Best regards,
Toshi

**Comment by KevScarr** [comment]
Can we include Scoring #85 in the next release?
Thanks,
Kevin.

**Comment by claraserranosolsona** [comment]
Thanks Kevin

This would be our proposal as well, to include KYC match v0.2 with Scoring #85 scope in the next meta release, and aligned with the appropiate commonalities

Regards,
Clara

**Comment by ToshiWakayama-KDDI** [comment]
Hi all,

KDDI would like to include KYC Fill-in (v0.1) in the next Fall24 meta release.

Thanks.
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Closed, as ageed at the SP meeting on 2024-10-01.
