### ISSUE TITLE
Add initials to the attribute list

### ISSUE THREAD

**Issue by HuubAppelboom** [camaraproject/KnowYourCustomer#77]
At KPN (and maybe at other telco's as well) we ony store our customers initials, not the givenName and middleNames in full.

For example my data is stored as HM Appelboom, where HM are my initials, and Appelboom is my familyName.
(Hubertus is my givenName and Mattheus my middleName).

We considered using the givenName and middleNames field, but this may give a faulty impression to the API consumer that there is a full match on givenName and middleNames, while in reality there is only a match being done on the initials.

We therefore propose to add an attribute which contains the  initials of givenName and middleNames. 

I suggest to call this initialsGivenMiddleNames (to make sure people don't add the initial of the family name as well).

**Comment by KevScarr** [comment]
@HuubAppelboom Is this common practice for all operators in your market? I'm wondering how an Aggregator would know to use initial letter of full name, or should they be providing both, otherwise proposal looks practical to me.

**Comment by HuubAppelboom** [comment]
@KevScarr With the current Mobile Connect product we agreed in the NL market to work only with initials, because some Telco's only store the initials, and several of our customers have the same issue.

For the CAMARA version we are proposing to support both in the specification, so we don't need to make country specific adaptations.  API cosumers can then decide what they want to supply, and the answer can also be tailored to what the MNO can support.

**Comment by HuubAppelboom** [comment]
Alternatively, we can also call this field initials, as long as the description is 100% clear what the initials cover (first name and middle names)

**Comment by HuubAppelboom** [comment]
All, as discussed in todays meeting, it may be better in stead of using a seperate attribute for initials, to provide an answer "only_initials" next to the current "true" or "false" for the match response for givenName and middleNames.

**Comment by HuubAppelboom** [comment]
In case KPN is the only Telco having this issue (we only have Initials stored in our database), we can also work that we match givenName adnd middleNames, but only for the initials, and inform parties during the onboarding process as an exception.

If  there are not many other parties with this issue, we propose to close the issue

**Comment by ToshiWakayama-KDDI** [comment]
Issue closed as agreed in the 2024-10-15 meeting.
