### ISSUE TITLE
Tenure API to be handled in KYC-SP regular meetings and ML

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/KnowYourCustomer#92]
**Problem description**
**Expected action**

Hi all,

As you may be aware, CAMARA TSC approved of start of Tenure API work last week.  Tenure API will have its own Sub project/Repository and Maintainers, but it will use KYC-SP ML and KYC-SP regular meeting slots (with MoMs shared).  The main reason was that it is likely that KYC-SP and Tenure-SP will have a significant overlap of Maintainers.  

If you have any problem or concerns with Tenure API using KYC-SP ML and KYC-SP regular meeting slots (with MoMs shared), please raise your hand.

BR
Toshi

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , that's ok and a good idea. Thanks
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Closed as confirmed in the meeting 2024-06-11: Tenure API is now handled as part of KnowYourCustomer API family, as CAMARA TSC decided.

Thanks.
