### ISSUE TITLE
Update and review CODEOWNERS and MAINTAINERS.md file

### ISSUE THREAD

**Issue by hdamker** [camaraproject/KnowYourCustomer#97]
**Problem description**

Update CODEOWERNS and MAINTAINERS.md as per points 3 and 7 of https://github.com/camaraproject/Governance/issues/134
and ensure that all Maintainers and Codeowners have accepted the invite into the CAMARA GitHub organization.

**Expected action**

Create PR for the updates.
Review the current Maintainer list.

**Additional context**

**Comment by ToshiWakayama-KDDI** [comment]
Hi @hdamker ,

Thanks very much for creating this issue as well as the corresponding PR #98.  I should have done this before you lost patience. :-)  Actually it's been in my action list for a long time.  It won't take time to approve, as it is a simple one and we have a regular meeting tomorrow where it can be confirmed.

BR
Toshi
